# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cs211/hexaworld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cs211/hexaworld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cs211/hexaworld/CMakeFiles /home/cs211/hexaworld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cs211/hexaworld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hexamap

# Build rule for target.
hexamap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hexamap
.PHONY : hexamap

# fast build rule for target.
hexamap/fast:
	$(MAKE) -f CMakeFiles/hexamap.dir/build.make CMakeFiles/hexamap.dir/build
.PHONY : hexamap/fast

#=============================================================================
# Target rules for targets named show

# Build rule for target.
show: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 show
.PHONY : show

# fast build rule for target.
show/fast:
	$(MAKE) -f CMakeFiles/show.dir/build.make CMakeFiles/show.dir/build
.PHONY : show/fast

#=============================================================================
# Target rules for targets named cellworld_tests

# Build rule for target.
cellworld_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cellworld_tests
.PHONY : cellworld_tests

# fast build rule for target.
cellworld_tests/fast:
	$(MAKE) -f lib/cellworld/CMakeFiles/cellworld_tests.dir/build.make lib/cellworld/CMakeFiles/cellworld_tests.dir/build
.PHONY : cellworld_tests/fast

#=============================================================================
# Target rules for targets named cellworld

# Build rule for target.
cellworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cellworld
.PHONY : cellworld

# fast build rule for target.
cellworld/fast:
	$(MAKE) -f lib/cellworld/CMakeFiles/cellworld.dir/build.make lib/cellworld/CMakeFiles/cellworld.dir/build
.PHONY : cellworld/fast

#=============================================================================
# Target rules for targets named ge211

# Build rule for target.
ge211: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ge211
.PHONY : ge211

# fast build rule for target.
ge211/fast:
	$(MAKE) -f lib/cellworld/lib/ge211/CMakeFiles/ge211.dir/build.make lib/cellworld/lib/ge211/CMakeFiles/ge211.dir/build
.PHONY : ge211/fast

#=============================================================================
# Target rules for targets named catch

# Build rule for target.
catch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 catch
.PHONY : catch

# fast build rule for target.
catch/fast:
	$(MAKE) -f lib/cellworld/lib/catch/CMakeFiles/catch.dir/build.make lib/cellworld/lib/catch/CMakeFiles/catch.dir/build
.PHONY : catch/fast

#=============================================================================
# Target rules for targets named gcomm

# Build rule for target.
gcomm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcomm
.PHONY : gcomm

# fast build rule for target.
gcomm/fast:
	$(MAKE) -f lib/gcomm/CMakeFiles/gcomm.dir/build.make lib/gcomm/CMakeFiles/gcomm.dir/build
.PHONY : gcomm/fast

src/hexamap.o: src/hexamap.cpp.o

.PHONY : src/hexamap.o

# target to build an object file
src/hexamap.cpp.o:
	$(MAKE) -f CMakeFiles/hexamap.dir/build.make CMakeFiles/hexamap.dir/src/hexamap.cpp.o
.PHONY : src/hexamap.cpp.o

src/hexamap.i: src/hexamap.cpp.i

.PHONY : src/hexamap.i

# target to preprocess a source file
src/hexamap.cpp.i:
	$(MAKE) -f CMakeFiles/hexamap.dir/build.make CMakeFiles/hexamap.dir/src/hexamap.cpp.i
.PHONY : src/hexamap.cpp.i

src/hexamap.s: src/hexamap.cpp.s

.PHONY : src/hexamap.s

# target to generate assembly for a file
src/hexamap.cpp.s:
	$(MAKE) -f CMakeFiles/hexamap.dir/build.make CMakeFiles/hexamap.dir/src/hexamap.cpp.s
.PHONY : src/hexamap.cpp.s

src/show.o: src/show.cpp.o

.PHONY : src/show.o

# target to build an object file
src/show.cpp.o:
	$(MAKE) -f CMakeFiles/show.dir/build.make CMakeFiles/show.dir/src/show.cpp.o
.PHONY : src/show.cpp.o

src/show.i: src/show.cpp.i

.PHONY : src/show.i

# target to preprocess a source file
src/show.cpp.i:
	$(MAKE) -f CMakeFiles/show.dir/build.make CMakeFiles/show.dir/src/show.cpp.i
.PHONY : src/show.cpp.i

src/show.s: src/show.cpp.s

.PHONY : src/show.s

# target to generate assembly for a file
src/show.cpp.s:
	$(MAKE) -f CMakeFiles/show.dir/build.make CMakeFiles/show.dir/src/show.cpp.s
.PHONY : src/show.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... hexamap"
	@echo "... install"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... show"
	@echo "... list_install_components"
	@echo "... cellworld_tests"
	@echo "... cellworld"
	@echo "... ge211"
	@echo "... catch"
	@echo "... gcomm"
	@echo "... src/hexamap.o"
	@echo "... src/hexamap.i"
	@echo "... src/hexamap.s"
	@echo "... src/show.o"
	@echo "... src/show.i"
	@echo "... src/show.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

