#!/bin/bash

cd ..
A=$(git show | grep commit)
hexaworld_version=$(echo $(echo "$A" | cut -d' ' -f 2 ))
cd - >> /dev/null
cd ../../cellworld
A=$(git show | grep commit)
cellworld_version=$(echo $(echo "$A" | cut -d' ' -f 2 ))
cd - >> /dev/null

printf "\"hexaworld_commit\": \"$hexaworld_version\", \"cellworld_commit\": \"$cellworld_version\""