#!/bin/bash

if (($# < 6))
then
  echo "usage:"
  echo "   run_world [sim_number] [entropy] [repetitions] [planning_iteration] [k] [pred_starting_pos1] [pred_starting_pos2] [pred_starting_pos3] [pred_starting_pos4]... "
  echo "   pred_starting_pos format: (x;y) "
else
    world="OcclusionCoordinates_$1_$2"
    R=$#
    start=`date +%s`
    echo "World $world started"
    echo "{ 'episodes': [" > ${7}${world}.log
    for ((I=8;I<=$R;I++))
    do
        tuple=${!I}
        x=$(echo "$tuple" | cut -d';' -f 1 | cut -d'(' -f 2)
        y=$(echo "$tuple" | cut -d';' -f 2 | cut -d')' -f 1)
        ./run_episode $3 $world ${7}${world} $4 $5 $x $y $6
    done
    echo "]}" >> ${7}${world}.log
    end=`date +%s`
    runtime=$((end-start))

    echo "World $world completed. Exec time $runtime"
fi