#!/bin/bash
if (($# < 6))
then
  echo "usage:"
  echo "   run_all experiments_file experiment_name repetitions planning_iterations particles randomness path_type"
else
  experiments_file=$1
  experiment_name=$2
  repetitions=$3
  planning_iteration=$4
  particles=$5
  randomness=$6
  path_type=$7
  results_folder="/home/german/simulation/results"

  if [[ ! -f $experiments_file ]]
  then
      echo "Can't process. Experiment file '$experiments_file' not found."
      exit
  fi

  if [[ -d $results_folder/$experiment_name ]]
  then
      echo "Can't process. Result folder '$results_folder/$experiment_name' already exists."
      exit
  fi

  start=$(date +%s)
  file_prefix=$results_folder/$experiment_name
  mkdir "$file_prefix" 2> /dev/null

  echo "./run_all $experiments_file $experiment_name $repetitions $planning_iteration $particles $randomness $path_type" > "${file_prefix}/script.sh"

  cp "$experiments_file" "$file_prefix"

  while IFS="" read -r p || [ -n "$p" ]
  do
    simulation=$(echo "$p" | cut -d' ' -f 1)
    entropy=$(echo "$p" | cut -d' ' -f 2)
    start_locations=$(echo "$p" | cut -d'"' -f 2)
    worker -w 18 -c "./run_world $simulation $entropy $repetitions $planning_iteration $particles $randomness $file_prefix $path_type $start_locations"
    cp "world_${simulation}_${entropy}.csv" "$file_prefix"
  done < "$experiments_file"

  worker -w 1 -c "echo"

  end=$(date +%s)
  runtime=$((end-start))

#  cd ../../visualizer
#  python3 survival.py $experiment_name > ${file_prefix}/summary.txt
#  cd - > /dev/null
#  cd $results_folder
#  git add --all
#  git commit --all --message "none"
#  git push
#  cd -
  echo "Done. Exec time: $runtime"
fi