#!/bin/bash

if (($# < 6))
then
  echo "usage:"
  echo "   run_world [sim_number] [entropy] [repetitions] [planning_iteration] [particles] [path_type] [pred_starting_pos1] [pred_starting_pos2] [pred_starting_pos3] [pred_starting_pos4]... "
  echo "   pred_starting_pos format: (x;y) "
else
    world="world_$1_$2"
    log_file=$(echo "${7}/${world}.log")
    R=$#
    start=`date +%s`
    echo "World $world started"
    cn=$(./get_commit_number)
    echo "{ 'result_set_name': '$7', 'code_version': { $cn }, 'episodes': [" > $log_file
    for ((I=9;I<=$R;I++))
    do
        tuple=${!I}
        x=$(echo "$tuple" | cut -d';' -f 1 | cut -d'(' -f 2)
        y=$(echo "$tuple" | cut -d';' -f 2 | cut -d')' -f 1)
        ./run_episode $3 $world $log_file $4 $5 $x $y $6 $8
    done
    echo "]}" >> $log_file
    end=`date +%s`
    runtime=$((end-start))

    echo "World $world completed. Exec time $runtime"
fi