#!/bin/bash

if (($# < 5)); then
  exit
fi

experiment_name=$1
shift
world_name=$1
shift
group_name=$1
shift
set_name=$1
shift
results_folder="/home/german/simulation/results/$experiment_name"
set_folder=$results_folder/$group_name/$world_name/$set_name

mkdir $set_folder -p

result_file=${set_folder}/episodes.json
#worker -s "$set_name of $world_name"

configuration="$@"
command="habit $world_name $configuration"
result=$(./$command)
if [ $? -ne 0 ]; then
  echo "FAILED: $command" >> "$results_folder/errors.err"
else
  printf "{ \"experiment_name\": %s, \"group_name\": %s, \"world_name\": %s, \"set_name\": %s, \"command\": \"%s\", \"episodes\": %s }" "$experiment_name" "$group_name" "$world_name" "$set_name" "$command" "$result" > "$result_file"
fi

