#!/bin/bash

_dfiles="*.csv"

FILECOUNT=$(ls $_dfiles | wc -l)

WORKERS=$(dc -e "[$FILECOUNT]sM $2d $FILECOUNT<Mp")

echo "Starting training of $FILECOUNT worlds on $WORKERS workers"

R=$1
for ((I=1;I<=$R;I++))
do
  for f in $_dfiles
  do
    NAME=`echo "$f" | cut -d'.' -f1`
    echo "launching $I $NAME..."
    worker -w $WORKERS -c "./train_world $NAME"
  done
done

worker -w 1 -c "echo Done!"
